version: "3"
services:
  neko:
    build:
      context: .
      dockerfile: Dockerfile.custom
    image: "neko-screenshare:latest"
    restart: "always"
    shm_size: "2gb"
    ports:
      - "8080:8080" # Web interface
      - "52000-52100:52000-52100/udp" # WebRTC video/audio stream
    environment:
      NEKO_SCREEN: 1920x1080@30
      NEKO_PASSWORD: "neko"
      NEKO_PASSWORD_ADMIN: "admin"
      NEKO_BIND: :8080
      NEKO_EPR: 52000-52100
      NEKO_ICELITE: "true"
      NEKO_NAT1TO1: 192.168.1.102
      NEKO_CONTROL_PROTECTION: "false"
      NEKO_IMPLICIT_CONTROL: "true"
